### ISSUE TITLE
Disappearing suggestions in Mozc for Android on LineageOS 21 (Android 14)

### ISSUE THREAD

**Issue by seppiola** [petlyh/JS-Dict#10] opened 2024-06-08 17:25 UTC
Suggestions for words for mozc android often disappear after kana input in js-dict on android 14.
Sometimes they stay in the word candidate section on top of the keyboard but often disappear immediately after a word update.
Apparently the space key used to select among the candidates does not trigger the disappeqrence of the top bar.
Here is a short recording, typing two different words the issue presents itself in slightly different ways:

https://github.com/petlyh/JS-Dict/assets/20034870/b9dce919-6198-4749-bb7d-741451fb7e8c

This is how it's supposed to work instead:

https://github.com/petlyh/JS-Dict/assets/20034870/e76d5ca0-1b3e-44f3-8f51-7352106fe75f

I know mozc for android is relatively old and unmaintained, and that it targets old android APIs but it's the only foss japanese ime available on android without gapps or gboard, specifically with 12 keys input, and works in every app with text input I tried on android 14 showing this strange beheaviour only in js-dict so this might be solved with relatively low effort.
I can't reproduce the issue on android 9 (LineageOS 16) where it works as intended.

**Comment by petlyh** [comment] 2024-06-08 22:27
Duplicate of #6.
This is a known problem in the Flutter framework that this app uses and is not caused by a specific IME (though the bug seems to only cause problems in Mozc-based IMEs). Since I can't reproduce the issue, I'm unfortunately unable to attempt to fix it.

**Closed by petlyh** 2024-06-08 22:27 UTC
Labels: bug, duplicate

**Comment by seppiola** [comment] 2024-06-09 10:26
I'm sorry I thought I checked older issues... I was clearly mistaken.
I confirm it appens only on certain versions of android, for instance on my android 9 the issue is not present and not reproducible.
Hope it gets resolved upstream in flutter than, thank you anyway.
